### ISSUE TITLE
ImportError cannot import name 'etree'

### ISSUE THREAD

**Issue by a327777892** [ASAS1314/jd_subscribe_seckill#5]
这个怎么处理啊

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ASAS1314** [comment]
依赖没装好

**Comment by a327777892** [comment]
请问手机版的Pythonista如何直接安装 requirements.txt 文件里面所有的库啊,用文档里面的安装指令不行。

**Comment by ASAS1314** [comment]
> 请问手机版的Pythonista如何直接安装 requirements.txt 文件里面所有的库啊,用文档里面的安装指令不行。
